version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  streamlit_app:
    build: .
    container_name: streamlit
    depends_on:
      - mongodb
    ports:
      - "8501:8501"
    environment:
      - MONGO_URI=mongodb://mongo:27017
    volumes:
      - .:/app
    restart: always

volumes:
  mongo_data:
